### ISSUE TITLE
python 3.10.6 import error

### ISSUE THREAD

**Issue by xuenhappy** [scottkmaxwell/pbjson#5] opened 2022-11-04 10:13 UTC
>>> import pbjson
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/dist-packages/pbjson/__init__.py", line 84, in <module>
    from . import encoder
  File "/usr/local/lib/python3.10/dist-packages/pbjson/encoder.py", line 13, in <module>
    from collections import Mapping
ImportError: cannot import name 'Mapping' from 'collections' (/usr/lib/python3.10/collections/__init__.py)

------

must fix  'from collections' to  'from collections.abc',best try catch

**Comment by Edgxxar** [comment] 2023-07-04 10:22
I have encountered this issue today, it turns out the latest release of this project on PyPi is outdated (https://pypi.org/project/pbjson/). The issue is already fixed with commit [#6058a20](https://github.com/scottkmaxwell/pbjson/commit/6058a201d20e43acec42979acdd1703dd7361763), you can install the most recent version from git, for example using pipenv:

`pipenv install -e git+https://github.com/scottkmaxwell/pbjson@master#egg=pbjson`

Maybe @scottkmaxwell can push a new release to PyPi?

**Comment by scottkmaxwell** [comment] 2023-07-06 05:13
I had to completely update how I publish. Finally got 1.16.0 out!

**Closed by scottkmaxwell** 2023-07-06 05:13 UTC
